# Generated by Django 3.1.1 on 2020-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="image",
            field=models.ImageField(blank=True, upload_to="profile_image"),
        ),
    ]
