# Generated by Django 3.1.1 on 2020-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0004_auto_20200903_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
