# Generated by Django 3.1.1 on 2020-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0006_auto_20200903_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="image",
            field=models.ImageField(
                blank=True,
                default="func/images/default.png",
                null=True,
                upload_to="images",
            ),
        ),
    ]
