# Generated by Django 3.1.1 on 2020-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0008_auto_20200903_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="imagem",
            field=models.ImageField(
                default="func/images/default.png", null=True, upload_to="images"
            ),
        ),
    ]
